name: Test steps

on:
  pull_request:

env:
  LABEL: enqueue
  MISSING_LABEL: missing

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Check for present label
        uses: egmacke/action-check-label@v1
        with:
          label: ${{ env.LABEL }}
          state: 'present'
